name: Compile MongoDB for ARMv8-a

on:
  push:
    branches: [ v8.0 ]
  pull_request:
    branches: [ v8.0 ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push MongoDB for ARMv8-a
      run: |
        docker buildx create --use
        docker buildx build --platform linux/arm64 -t ghcr.io/${{ github.repository }}/mongodb-armv8a:latest --push .
